name: Waka
on:
  schedule:
    - cron: '0 0 * * *'
    workflow_dispatch:
jobs:
  waka:
    name: Waka
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
